#define EXP_PROPERTY_SAVE_OBJECTS (1 << 0)
#define EXP_PROPERTY_SAVE_TURFS (1 << 1)
#define EXP_PROPERTY_SAVE_AREAS (1 << 2)

#define EXP_PROPERTY_SAVE_DEFAULT (EXP_PROPERTY_SAVE_OBJECTS | EXP_PROPERTY_SAVE_TURFS | EXP_PROPERTY_SAVE_AREAS)

#define EXP_PROPERTY_DMM_HEADER "//MAP CONVERTED BY dmm2tgm.py THIS HEADER COMMENT PREVENTS RECONVERSION, DO NOT REMOVE"
