#define CTAG_EXPERIMENTAL_BANKER "CAT_EXPERIMENTAL_BANKER"
#define CTAG_EXPERIMENTAL_LANDLORD "CAT_EXPERIMENTAL_LANDLORD"

#define JDO_EXPERIMENTAL_BANKER 17.05
#define JDO_EXPERIMENTAL_LANDLORD 17.06
